### ISSUE TITLE
Python 3 syntax errors

### ISSUE THREAD

**Issue by cclauss** [sobotka/blender#2]
$ __time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./build_files/package_spec/build_archive.py:32:17: E999 SyntaxError: invalid syntax
except Exception, ex:
                ^
./source/blender/python/simple_enum_gen.py:42:38: E999 SyntaxError: invalid syntax
print '\tmod = PyModule_New("dummy");'
                                     ^
```
Solutions that work in both Python 2 and Python 3:
1. __except Exception, ex:__ --> __except Exception as ex:__
2. __print '\tmod = PyModule_New("dummy");'__ --> __print('\tmod = PyModule_New("dummy");')__

**Comment by sobotka** [comment]
This is a mirror. Go report to the official tracker.
