### ISSUE TITLE
It's a me, mendio

### ISSUE THREAD

**Issue by mendio** [sobotka/blender#5]
Hey, I'm aware this isn't an issue per say, but I'm not sure how to contact you.

Every time you mention `@mendio` GitHub sends me a notification via email, the thing is I never contributed to blender.

I dug a bit and I'm fairly sure the guy supposed to get the notifications/credit is https://twitter.com/mmendio but it doesn't seem like he has a github account.

See:
https://github.com/sobotka/blender/commit/057117de
https://github.com/sobotka/blender/commit/bb9c9d0

**Comment by sobotka** [comment]
It stinks, but sadly I can’t mute the notifications as it is simply a mirror.

**Comment by Blendify** [comment]
Above the repository set the watch mode to "Ignoring"
