### ISSUE TITLE
Missing 'any' in COPYING file

### ISSUE THREAD

**Issue by gsc2001** [sobotka/blender#9]
In COPYING file it would be more clear if 'any' was there after under 
     
     Apart from the GNU GPL, Blender is not available under other licenses.

It would be more clear if it was like this

     Apart from the GNU GPL, Blender is not available under any other licenses.

**Comment by gsc2001** [comment]
I am a beginner can this issue be assigned to me ?

**Comment by sobotka** [comment]
This is a mirror.
